<?php
// $Id$

/**
 * @file
 * An example to define a simple field, widget, and formatter.
 * A module could define only a field, only a widget, only a
 * formatter, or any combination. Widgets and formatters must
 * declare what kind of field they work with, which can be any
 * existing field as well as any new field the module creates.
 * @author Michael Prasuhn <mike@shomeya.com>
 * @link http://shomeya.com
 * @package crm_fields
 */

/**
 * Implementation of hook_form_alter().
 *
 * Add option to field group settings form to include item default reordering.
 */
function crm_fields_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'fieldgroup_group_edit_form') {
    $form['settings']['multigroup']['default-order'] = array(
      '#type' => 'checkbox',
      '#title' => 'Default ordering',
      '#default_value' => variable_get('crm_fields.default-order.' . $form['group_name']['#default_value'], 0),
      '#description' => t('Enable this option to add an option to each group to set that group as default (show up first).'),
      '#weight' => -1,
    );
    $form['#submit'][] = 'crm_fields_form_fieldgroup_group_edit_form_submit';
  }
}

/**
 * Submit callback for field group forms.
 */
function crm_fields_form_fieldgroup_group_edit_form_submit($form, &$form_state) {
  variable_set('crm_fields.default-order.' . $form_state['values']['group_name'], $form_state['values']['settings']['multigroup']['default-order']);
}
