<?php
// $Id$

/**
 * Implementation of hook_form_alter().
 *
 * Add option to field group settings form to include item default reordering.
 */
function multigroup_default_order_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'fieldgroup_group_edit_form') {
    $form['settings']['multigroup']['default-order'] = array(
      '#type' => 'checkbox',
      '#title' => 'Default ordering',
      '#default_value' => variable_get('multigroup_default_order.default-order.' . $form['group_name']['#default_value'], 0),
      '#description' => t('Enable this option to add an option to each group to set that group as default (show up first).'),
      '#weight' => -1,
    );
    $form['#submit'][] = 'multigroup_default_order_form_fieldgroup_group_edit_form_submit';
  }
}

/**
 * Submit callback for field group forms.
 */
function multigroup_default_order_form_fieldgroup_group_edit_form_submit($form, &$form_state) {
  variable_set('multigroup_default_order.default-order.' . $form_state['values']['group_name'], $form_state['values']['settings']['multigroup']['default-order']);
}
